[package]
name = "pdfexporter_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
image = { version = "0.24.7", package = "image" }
image_crate = { version = "0.23.14", package = "image" }
printpdf = {version="0.5.3", features = ["embedded_images"]} 
idreader_lib = { path = "../idreader_lib" }
